package com.basejava.util;

public enum DataType {
    PHONE_NUMBER,
    EMAIL,
    POSITION,
    PERSONAL,
    ACHIEVEMENT,
    QUALIFICATION,
    WORK_TITLE,
    WORK_DESCRIPTION,
    DATE,
    COMPANY_WEBSITE,
    COMPANY_NAME,
    EDUCATION_NAME,
    EDUCATION_WEBSITE,
    EDUCATION_TITLE,
    EDUCATION_DESCRIPTION
}
